DROP DATABASE IF EXISTS quiz;

CREATE DATABASE quiz;

USE quiz;

CREATE TABLE scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
